### ISSUE TITLE
Setting default address

### ISSUE THREAD

**Issue by webstik** [BNMetrics/Laravel-ShopifyAPI#12]
Hello,

I'm trying to modify the default address of the customer . For that purpose I'm trying to use the endpoint (https://help.shopify.com/api/reference/customer_address#default) **modifyCustomersAddressesDefault** in this way:
`$shopify->modifyCustomersAddressesDefault(['customer_id'=>'447150227516', 'address_id'=>'525468663868']);`
and in this way:
`$shopify->modifyCustomersAddressesDefault('447150227516','525468663868');`

in shopify.php I have :
```
'endpoints'   => [
....
        'customers'          => [
            'addresses'
        ]
];
```

but it produced following error:
`Exception:  Must define tier one endpoint! in file /home/vagrant/code/power-app/vendor/bnmetrics/laravel-shopify-api/src/Endpoints.php on line 83`

So, what is the correct way to modify the customer's default address?

**Comment by BNMetrics** [comment]
Hi there @webstik 
Sorry for the late response.

Since ``default`` is not one of the standard "All", "Count", "ById" call, you will need to include the last part of parameter like this:

```
$shopify->modifyCustomersAddressesById('default', ['customer_id'=>'447150227516', 'address_id'=>'525468663868']);

```

Hope it helps!
Luna

**Comment by webstik** [comment]
Actually the way to do that is with this:

```
$shopify->modifyCustomersAddresses('default', 447150227516, 525468663868);
```
