### ISSUE TITLE
shopify.php config file not generated

### ISSUE THREAD

**Issue by baberuth22** [BNMetrics/Laravel-ShopifyAPI#2]
I run 
$: php artisan vendor:publish --tag=shopify
Publishing complete.

But the file is not generated in app/config.   Tried setting all files to 777, but still no shopify.php generated.

**Comment by baberuth22** [comment]
Should I manually copy /vendor/bin/bnmetrics/laravel-shopif-api/src/config/shopify.php to /app/config/shopify.php?

**Comment by BNMetrics** [comment]
Hi there @baberuth22, I think with the auto package discovery, there is a bit of issue with laravel 5.4

Try running the following commands:
php artisan config:clear
php artisan cache:clear
php artisan vendor:publish --provider='BNMetrics\Shopify\ShopifyServiceProvider'

Let me know if this works.

Thanks!
