### ISSUE TITLE
How to make it work on laravel 6.x

### ISSUE THREAD

**Issue by eosvn** [BNMetrics/Laravel-ShopifyAPI#25]
Now I can not install it in Laravel 6.4, someone can help this issue? Thanks

**Comment by positivesquare** [comment]
I am looking for a solution too, but looks like the interest has been lost by the developer.
Too bad.

**Comment by eosvn** [comment]
> I am looking for a solution too, but looks like the interest has been lost by the developer.
> Too bad.

I have found an alternative. It is quite clear and easy to use. 
https://packagist.org/packages/ohmybrew/basic-shopify-api

**Comment by hoangphidev** [comment]
> > I am looking for a solution too, but looks like the interest has been lost by the developer.
> > Too bad.
> 
> I have found an alternative. It is quite clear and easy to use.
> https://packagist.org/packages/ohmybrew/basic-shopify-api

Thanks for your suggestion. I have successfully installed this package https://packagist.org/packages/ohmybrew/basic-shopify-api into project laravel 8x instead of using the current one. :))))

**Comment by eosvn** [comment]
> > > I am looking for a solution too, but looks like the interest has been lost by the developer.
> > > Too bad.
> > 
> > 
> > I have found an alternative. It is quite clear and easy to use.
> > https://packagist.org/packages/ohmybrew/basic-shopify-api
> 
> Thanks for your suggestion. I have successfully installed this package https://packagist.org/packages/ohmybrew/basic-shopify-api into project laravel 8x instead of using the current one. :))))

Thanks bờ rô 👍 :)))))
