### ISSUE TITLE
Private App

### ISSUE THREAD

**Issue by keyurshah** [BNMetrics/Laravel-ShopifyAPI#3]
This looks wonderful! In the readme it says that Private Apps are supported. I couldn't how to set that up in the code. I see information for public app, but not on setting private app credentials. 

Thanks.

**Comment by baberuth22** [comment]
pass your private API password.

    $this->api = Shopify::retrieve($shop_url, $password);
    $response = $this->api->get($call, $params);

**Comment by BNMetrics** [comment]
@keyurshah 
Just as @baberuth22  said, you can pass in your private API token for private apps.

**Comment by keyurshah** [comment]
Ok thanks! I will try it out
