### ISSUE TITLE
{"errors":{"metafield":"expected String to be a Hash"}}

### ISSUE THREAD

**Issue by baberuth22** [BNMetrics/Laravel-ShopifyAPI#4]
I am trying to get metafields and I end up with this error.

I believe it is related to this problem https://stackoverflow.com/questions/30767554/meteor-shopify-expected-string-to-be-a-hash because of nested params being sent.

**Comment by BNMetrics** [comment]
Hi @baberuth22 , if you are getting all the metafields, you could try this:
$this->api->getMetafieldsAll() to retrieve the meta fields, given $this->api being a Shopify object, and shopify.php in your /config directory. 

please let me know if it works out for you!

**Comment by baberuth22** [comment]
I got it.   It looks like my metafield were a json string rather than an object.   I simply had to json_decode($params['metafield']) before sending params to Shopify::retrieve.
