### ISSUE TITLE
Accessing response header data for API throttling?

### ISSUE THREAD

**Issue by roberttolton** [BNMetrics/Laravel-ShopifyAPI#6]
Hi, what would be the correct way of detecting the `HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT` header that Shopify sends back to try and account for rate-limit / throttling? I don't see this mentioned within the docs.

From what I can tell of the source, we're only returning decoded JSON, no request object or similar?

**Comment by BNMetrics** [comment]
Hi @roberttolton 
Unfortunately, currently I have not yet included the feature for getting the HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT. I might implement that on the next version of this package.

**Comment by roberttolton** [comment]
@BNMetrics did you have any more thoughts on this?
