### ISSUE TITLE
Post Fulfillment example?

### ISSUE THREAD

**Issue by roberttolton** [BNMetrics/Laravel-ShopifyAPI#7]
Hi,

The documentation is really unclear about how this is meant to work, could you please post an example of how to sent a `POST` request to the Fulfillment API?
https://help.shopify.com/api/reference/fulfillment#create

E.g: `/admin/orders/{$orderNumber}/fulfillments.json`

Thanks

**Comment by BNMetrics** [comment]
Hello @roberttolton 
With creation of fullfillment, you can do a call like so
```php
$options = [
'fulfillment' => [
    'tracking_number' => 'My tracking',
    "line_items" =>
      [
        "id" => 466157049
      ]
  ]
];

$orderID = 123456

$shop->createOrdersFillfilments($orderID, $options);

```

You can refer to this in the "CRUD requests to the API endpoints" in the documentation

Let me know if it helps!
Thanks!

**Comment by roberttolton** [comment]
Thanks for the example, however I'm now getting this error from Shopify:

```
{"errors":{"line_items":"expected Hash to be a Array"}}
```

But my JSON (`json_encode` of array) is exactly how the docs say they want it:

```
{
  "fulfillment": {
    "tracking_number": "EM530591543JP",
    "tracking_company": "EMS",
    "tracking_url": "https:\/\/trackings.post.japanpost.jp\/services\/srv\/search\/direct?searchKind=S004&locale=en&reqCodeNo1=EM530591543JP",
    "notify_customer": true,
    "line_items": [
      {
        "id": 12446456134
      }
    ]
  }
}
```

Any ideas? I saw a Shopify Forum post about Guzzle not formatting the data properly.. didn't go into anymore detail (https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/resolved-line_items-expected-hash-to-be-a-array-json-creating-order-402241).

**Comment by hamidxdev** [comment]
> Thanks for the example, however I'm now getting this error from Shopify:
> 
> ```
> {"errors":{"line_items":"expected Hash to be a Array"}}
> ```
> But my JSON (`json_encode` of array) is exactly how the docs say they want it:
> 
> ```
> {
>   "fulfillment": {
>     "tracking_number": "EM5305####JP",
>     "tracking_company": "EMS",
>     "tracking_url": "https:\/\/trackings.post.japanpost.jp\/services\/srv\/search\/direct?searchKind=S004&locale=en&reqCodeNo1=EM5305####JP",
>     "notify_customer": true,
>     "line_items": [
>       {
>         "id": 12446456134
>       }
>     ]
>   }
> }
> ```
> Any ideas? I saw a Shopify Forum post about Guzzle not formatting the data properly.. didn't go into anymore detail (https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/resolved-line_items-expected-hash-to-be-a-array-json-creating-order-402241).

did you resolve the issue , i have the same :/

**Comment by roberttolton** [comment]
@hamidxdev if you update to the latest version of this package, I'm pretty sure it's fixed as it's been working for me: https://github.com/BNMetrics/Laravel-ShopifyAPI/pull/10
